name: Update Stations Data

on:
  issue_comment:
    types: [created]

jobs:
  update-stations:
    if: |
      (github.event.issue.pull_request != null || github.event.issue.number != null) &&
      (contains(github.event.comment.body, ' /update station') ||
       startsWith(github.event.comment.body, '/update station'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Add reaction to trigger comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"
      
      - name: Install dependencies
        run: |
          uv sync --dev
      
      - name: Run station crawler
        run: |
          echo "🚀 Starting station data crawling..."
          uv run jp-transit crawl-stations \
            --output stations.csv \
            --format csv \
            --max-stations 0 \
            --delay 1.0
        
      - name: Check if stations.csv was created
        run: |
          if [ ! -f stations.csv ]; then
            echo "❌ Error: stations.csv was not created"
            exit 1
          fi
          echo "✅ stations.csv created successfully"
          echo "📊 Station count: $(wc -l < stations.csv)"
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit and push changes
        run: |
          git add stations.csv
          if git diff --staged --quiet; then
            echo "📝 No changes to commit"
            echo "CHANGES_MADE=false" >> $GITHUB_ENV
          else
            timestamp=$(date '+%Y-%m-%d %H:%M:%S UTC')
            station_count=$(tail -n +2 stations.csv | wc -l)
            commit_msg="📊 Update stations data - ${station_count} stations"$'\n\n'"Auto-generated by GitHub Action on ${timestamp}"$'\n'"Triggered by: @${{ github.event.comment.user.login }}"$'\n'"Issue/PR: #${{ github.event.issue.number }}"
            git commit -m "${commit_msg}"
            git push
            echo "CHANGES_MADE=true" >> $GITHUB_ENV
            echo "STATION_COUNT=${station_count}" >> $GITHUB_ENV
          fi
          
      - name: Comment on success
        if: env.CHANGES_MADE == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **Station data updated successfully!**
            
            📊 **Results:**
            - **Stations crawled:** ${{ env.STATION_COUNT }}
            - **File:** `stations.csv`
            - **Commit:** ${{ github.sha }}
            
            The latest station data has been committed to the repository. You can download the updated `stations.csv` file from the repository root.
            
            ---
            *Triggered by /update station command*
      
      - name: Comment on no changes
        if: env.CHANGES_MADE == 'false'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ℹ️ **No changes detected**
            
            The station crawling completed successfully, but no changes were detected in the data. The current `stations.csv` file is already up to date.
            
            ---
            *Triggered by /update station command*
      
      - name: Add success reaction
        if: success()
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: hooray
          
      - name: Comment on failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ❌ **Station data update failed**
            
            There was an error while crawling or updating the station data. Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
            
            Common issues:
            - Network connectivity problems during crawling
            - Rate limiting from the transit website
            - Parsing errors due to website changes
            
            ---
            *Triggered by /update station command*
      
      - name: Add failure reaction
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: confused